services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
      args:
        WEB_BUILDER_IMAGE: web_builder
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - api.hono
      - api.laravel
    networks:
      - actnote_default

  api.hono:
    build:
      context: .
      dockerfile: ./docker/hono.Dockerfile
    expose:
      - 3000
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres
    networks:
      - actnote_default

  api.laravel:
    build:
      context: .
      dockerfile: ./docker/laravel.Dockerfile
    expose:
      - 9000
    environment:
      APP_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - actnote_default

  postgres:
    image: postgres:17
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - actnote_default

  mysql:
    image: mysql:9
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - actnote_default

volumes:
  postgres_data:
  mysql_data:

networks:
  actnote_default:
    driver: bridge